Rarely in my days as a programmer have I battled so awkwardly to achieve some sort of answer: This breaks but as it falls through it's exhausted knees it hands the answer up to it's master and with it's dying breath it says "Array index out of bounds exception"
Literally this is the (pathetic) output:

checking 139 115 1523
checking 139 116 1523
checking 139 120 1523
checking 139 132 1523
checking 139 136 1524
checking 140 1 1524
Traceback (most recent call last):
  File "/Users/pauljones/dev/advent-of-code/2024/day20/01.py", line 36, in <module>
    c = find_path(start, end, grid)
  File "/Users/pauljones/dev/advent-of-code/2024/day20/a_star.py", line 20, in find_path
    for next_cost, next_pos in get_adjacent(
                               ~~~~~~~~~~~~^
        current[0],
        ^^^^^^^^^^^
        current[1],
        ^^^^^^^^^^^
        field,
        ^^^^^^
    ):
    ^
  File "/Users/pauljones/dev/advent-of-code/2024/day20/adjacents.py", line 5, in get_adjacent
    if grid[j + 1][i] != "#":
       ~~~~~~~~~~~^^^
IndexError: list index out of range
python3 01.py  129.58s user 1.77s system 98% cpu 2:13.05 total